package com.googol24.bbs;

import java.sql.*;

/**
 * DB Bean
 */
public class DB {
    public static Connection getConnection() {
        Connection connection = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost/bbs", "root", "root");
        } catch (ClassNotFoundException e) {
            System.out.println("Do not found the driver class!");
        } catch (SQLException e) {
            System.out.println("SQL Exception:" + e.getMessage());
            e.printStackTrace();
        }

        return  connection;
    }

    public static Statement getStatement(Connection connection) {
        Statement statement = null;

        try {
            statement = connection.createStatement();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return statement;
    }

    public static ResultSet executeQuery(Statement statement, String sql) {
        ResultSet resultSet = null;

        try {
            resultSet = statement.executeQuery(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return resultSet;
    }

    public static int executeUpdate(Connection connection, String sql) {
        int result = 0;
        Statement statement = null;

        try {
            statement = getStatement(connection);
            result = statement.executeUpdate(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            close(statement);
        }

        return result;
    }

    public static PreparedStatement preparedStatement(Connection connection, String sql) {
        PreparedStatement preparedStatement = null;

        try {
            preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return preparedStatement;
    }

    public static PreparedStatement preparedStatement(Connection connection, String sql, int autoGeneratedKeys) {
        PreparedStatement preparedStatement = null;

        try {
            preparedStatement = connection.prepareStatement(sql, autoGeneratedKeys);
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return preparedStatement;
    }

    public static void close(ResultSet resultSet) {
        try {
            resultSet.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void close(Statement statement) {
        try {
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void close(Connection connection) {
        try {
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
